### ISSUE TITLE
🚧Fix keyboard input issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#1062]
### Complete The Item Below

- [x] I have updated the title without removing the 🚧 emoji.

### Description

Fix an issue where using a keyboard with a special input, such as a special key or volume adjustment knob, crashes the running application.

This can be repeated by using the keyboard that @CalvinWilkinson owns. This keyboard comes with a rotary knob for adjusting the volume, and when using the knob, the application crashes.

It is unknown if the keyboard output when using the audio volume can be officially supported. Perform the research required to find out if this can be supported.

If the function can be officially supported, properly implement its use case. If not, account for unknown keyboard functionality and prevent the application from crashing.

### The items to complete to satisfy the Definition of Done.
- [x] All the unit tests have been executed and passed locally after the PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [x] The application does not crash when unknown special keyboard inputs are used

### The items to complete to satisfy the Definition of Done.
- [x] Add a change type label to the issue. Refer to the _**Change Type Labels**_ section below.
- [x] Add a priority label to the issue. Refer to the _**Priority Type Labels**_ section below.
- [x] Link the issue to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking-changes`      |
| New Feature              | `✨new-feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
I created the issue below with the Silk.NET project.

- dotnet/Silk.net#2407
- dotnet/Silk.net#2372

**Comment by CalvinWilkinson** [comment]
Put issue https://github.com/KinsonDigital/Velaptor/labels/on-hold until we get a response from the silk.net team

**Comment by Tweety-Lab** [comment]
This issue should be resolved in the latest Silk.NET build, unknown keys will no longer throw exceptions/crash the application.

**Comment by Romacat2** [comment]
As of Silk.NET version 2.22, the error still occurs, the application crashes after pressing the volume down/up buttons on the laptop keyboard

**Comment by CalvinWilkinson** [comment]
@Tweety-Lab Thanks for the heads up!

@Romacat2 I will definitely check this out.  I will be hopefully releasing this in the next release but I have to check it out myself and make any necessary adjustments.

Hoping to get to it soon. Busy with client work.  😉
